[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "core"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
reqwest = "0.12.12"
tokio = { version = "1.44.0", features = ["macros", "rt-multi-thread"] }
engine = { path = "../engine" }
